
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - image: testapp11.azurecr.io/test-repo:0.6
          name: my-app
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /weatherforecast
              port: 80
          envFrom:
            - secretRef:
                name: my-secret
            - configMapRef:
                name: my-config
          readinessProbe:
            httpGet:
              path: /weatherforecast
              port: 80
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: test
  labels:
    app: my-app
spec:
  #type: LoadBalancer
  selector:
    app: my-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: test
data:
  SECRET_VALUE: MTcyNzM0NjQK
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: test
data:
  WEATHER_SUMMARY: Chilling
---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: my-app
#   namespace: test
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: my-app
#   minReplicas: 1
#   maxReplicas: 3
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 80